---
- name: This playbook creates a file or dir
  hosts: all
  become: true

  tasks:
  - name: Creating a file
    file:
      path: /home/ansadmin/demofile
      state: touch 

  - name: Creating a directory
    file:
      path: /home/ansadmin/dir1
      state: absent

