---
- name: This playbook installs httpd/apache on RHEL vm
  hosts: webservers
  become: true

  tasks:
  - name: This task installs httpd package on RHEL
    yum:
      name: httpd
      state: installed

  - name: This task starts the httpd webserver
    service:
      name: httpd
      state: started 
