---
- name: This playbook installs multiple packages at the same time
  hosts: webservers
  become: true

  tasks:
  - name: Install packages
    yum:
      name: ['git','make','gzip','tree','wget','telnet']
      state: installed
