---
# tasks file for setup-apache

- name: Install httpd on RedHat family
  yum:
    name: httpd
    state: installed
  when: ansible_os_family == "RedHat"
  tags: install_httpd
  notify: start httpd service

- name: Install apache2 on Debian family
  apt:
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  tags: install_apache2
  notify: start apache2 service

- name: Copy index.html file to Ubuntu server
  copy:
    src: /opt/ansible/index.html
    dest: /var/www/html
    mode: 0666

- name: Ensure that default httpd port is {{ port }}
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^#Listen'
    insertafter: '^#Listen'
    line: Listen {{ port }}
  when: ansible_os_family == "RedHat"
  notify: restart httpd

- name: Ensure that default apache2 port is {{ port }}
  ansible.builtin.lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^#Listen'
    insertafter: '# /etc/apache2/sites-enabled/000-default.conf'
    line: Listen {{ port }}
  when: ansible_os_family == "Debian"
  notify: restart apache2
